default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tooljet_development
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD", '') %>
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>

test:
  <<: *default
  database: tooljet_test

production:
  <<: *default
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['PG_DB'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
  