apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet-server-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      component: tooljet-server
  template:
    metadata:
      labels:
        component: tooljet-server
    spec:
      containers:
        - name: server-container
          image: tooljet/tooljet-server-ce:latest
          imagePullPolicy: Always
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
          resources:
            limits:
              memory: "3000Mi"
              cpu: "500m"
            requests:
              memory: "3000Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              port: 3000
              path: /
            successThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 6
          env:
            - name: RAILS_ENV
              value: "production"
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: server
                  key: host  
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: server
                  key: user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: server
                  key: password
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: server
                  key: db
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: server
                  key: lockbox_key      
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: server
                  key: secret_key_base

                  imagePullSecrets:
        - name: registry-secret